export { ReactComponent as IconArrowRight } from "./icon-arrow-right.svg";
export { ReactComponent as IconSearch } from "./icon-search.svg";
export { ReactComponent as IconWallet } from "./icon-wallet.svg";
export { ReactComponent as IconTwitter } from "./icon-twitter.svg";
export { ReactComponent as IconDiscord } from "./icon-discord.svg";
export { ReactComponent as IconSocial3Dots } from "./icon-social-3-dots.svg";
export { ReactComponent as IconLightning } from "./icon-lightning.svg";
export { ReactComponent as IconLayoutArrowDown } from "./icon-layout-arrow-down.svg";
export { ReactComponent as IconThunder } from "./icon-thunder.svg";
