/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.38.1
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

export type { OpenBetaNftAbi } from './OpenBetaNftAbi';

export { OpenBetaNftAbi__factory } from './factories/OpenBetaNftAbi__factory';
