/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.1
  Forc version: 0.60.0
  Fuel-Core version: 0.27.0
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Option, Enum } from "./common";

export enum AccessErrorInput { CannotReinitialized = 'CannotReinitialized', NotOwner = 'NotOwner' };
export enum AccessErrorOutput { CannotReinitialized = 'CannotReinitialized', NotOwner = 'NotOwner' };
export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;
export enum SideInput { Buy = 'Buy', Sell = 'Sell' };
export enum SideOutput { Buy = 'Buy', Sell = 'Sell' };
export enum ThunderExchangeErrorsInput { OnlyOwner = 'OnlyOwner', Initialized = 'Initialized', AmountHigherThanPoolBalance = 'AmountHigherThanPoolBalance', AssetIdNotMatched = 'AssetIdNotMatched', AmountNotMatched = 'AmountNotMatched', StrategyMustBeNonZeroContract = 'StrategyMustBeNonZeroContract', StrategyNotWhitelisted = 'StrategyNotWhitelisted', MakerMustBeNonZeroAddress = 'MakerMustBeNonZeroAddress', TakerMustBeNonZeroAddress = 'TakerMustBeNonZeroAddress', CallerMustBeMaker = 'CallerMustBeMaker', ExpirationRangeOutOfBound = 'ExpirationRangeOutOfBound', NonceMustBeNonZero = 'NonceMustBeNonZero', PriceMustBeNonZero = 'PriceMustBeNonZero', AmountMustBeNonZero = 'AmountMustBeNonZero', AssetNotSupported = 'AssetNotSupported', ExecutionInvalid = 'ExecutionInvalid', PaymentAssetMismatched = 'PaymentAssetMismatched', PriceMismatched = 'PriceMismatched', AmountMismatched = 'AmountMismatched', PoolTransferFromFailed = 'PoolTransferFromFailed', PoolMismatchedAssetBalance = 'PoolMismatchedAssetBalance' };
export enum ThunderExchangeErrorsOutput { OnlyOwner = 'OnlyOwner', Initialized = 'Initialized', AmountHigherThanPoolBalance = 'AmountHigherThanPoolBalance', AssetIdNotMatched = 'AssetIdNotMatched', AmountNotMatched = 'AmountNotMatched', StrategyMustBeNonZeroContract = 'StrategyMustBeNonZeroContract', StrategyNotWhitelisted = 'StrategyNotWhitelisted', MakerMustBeNonZeroAddress = 'MakerMustBeNonZeroAddress', TakerMustBeNonZeroAddress = 'TakerMustBeNonZeroAddress', CallerMustBeMaker = 'CallerMustBeMaker', ExpirationRangeOutOfBound = 'ExpirationRangeOutOfBound', NonceMustBeNonZero = 'NonceMustBeNonZero', PriceMustBeNonZero = 'PriceMustBeNonZero', AmountMustBeNonZero = 'AmountMustBeNonZero', AssetNotSupported = 'AssetNotSupported', ExecutionInvalid = 'ExecutionInvalid', PaymentAssetMismatched = 'PaymentAssetMismatched', PriceMismatched = 'PriceMismatched', AmountMismatched = 'AmountMismatched', PoolTransferFromFailed = 'PoolTransferFromFailed', PoolMismatchedAssetBalance = 'PoolMismatchedAssetBalance' };

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type AssetIdInput = { bits: string };
export type AssetIdOutput = AssetIdInput;
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type ExtraParamsInput = { extra_address_param: AddressInput, extra_contract_param: ContractIdInput, extra_u64_param: BigNumberish };
export type ExtraParamsOutput = { extra_address_param: AddressOutput, extra_contract_param: ContractIdOutput, extra_u64_param: BN };
export type MakerOrderInput = { side: SideInput, maker: AddressInput, collection: ContractIdInput, token_id: string, price: BigNumberish, amount: BigNumberish, nonce: BigNumberish, strategy: ContractIdInput, payment_asset: AssetIdInput, start_time: BigNumberish, end_time: BigNumberish, extra_params: ExtraParamsInput };
export type MakerOrderOutput = { side: SideOutput, maker: AddressOutput, collection: ContractIdOutput, token_id: string, price: BN, amount: BN, nonce: BN, strategy: ContractIdOutput, payment_asset: AssetIdOutput, start_time: BN, end_time: BN, extra_params: ExtraParamsOutput };
export type MakerOrderInputInput = { side: SideInput, maker: AddressInput, collection: ContractIdInput, token_id: string, price: BigNumberish, amount: BigNumberish, nonce: BigNumberish, strategy: ContractIdInput, payment_asset: AssetIdInput, expiration_range: BigNumberish, extra_params: ExtraParamsInput };
export type MakerOrderInputOutput = { side: SideOutput, maker: AddressOutput, collection: ContractIdOutput, token_id: string, price: BN, amount: BN, nonce: BN, strategy: ContractIdOutput, payment_asset: AssetIdOutput, expiration_range: BN, extra_params: ExtraParamsOutput };
export type OrderCanceledInput = { user: AddressInput, strategy: ContractIdInput, side: SideInput, nonce: BigNumberish };
export type OrderCanceledOutput = { user: AddressOutput, strategy: ContractIdOutput, side: SideOutput, nonce: BN };
export type OrderExecutedInput = { order: TakerOrderInput };
export type OrderExecutedOutput = { order: TakerOrderOutput };
export type OrderPlacedInput = { order: MakerOrderInput };
export type OrderPlacedOutput = { order: MakerOrderOutput };
export type OrderUpdatedInput = { order: MakerOrderInput };
export type OrderUpdatedOutput = { order: MakerOrderOutput };
export type OwnershipRenouncedInput = { previous_owner: IdentityInput };
export type OwnershipRenouncedOutput = { previous_owner: IdentityOutput };
export type OwnershipSetInput = { new_owner: IdentityInput };
export type OwnershipSetOutput = { new_owner: IdentityOutput };
export type OwnershipTransferredInput = { new_owner: IdentityInput, previous_owner: IdentityInput };
export type OwnershipTransferredOutput = { new_owner: IdentityOutput, previous_owner: IdentityOutput };
export type TakerOrderInput = { side: SideInput, taker: AddressInput, maker: AddressInput, nonce: BigNumberish, price: BigNumberish, token_id: string, collection: ContractIdInput, strategy: ContractIdInput, extra_params: ExtraParamsInput };
export type TakerOrderOutput = { side: SideOutput, taker: AddressOutput, maker: AddressOutput, nonce: BN, price: BN, token_id: string, collection: ContractIdOutput, strategy: ContractIdOutput, extra_params: ExtraParamsOutput };

interface ThunderExchangeAbiInterface extends Interface {
  functions: {
    cancel_order: FunctionFragment;
    execute_order: FunctionFragment;
    get_asset_manager: FunctionFragment;
    get_execution_manager: FunctionFragment;
    get_max_expiration: FunctionFragment;
    get_min_expiration: FunctionFragment;
    get_pool: FunctionFragment;
    get_protocol_fee_recipient: FunctionFragment;
    get_royalty_manager: FunctionFragment;
    get_transfer_selector: FunctionFragment;
    initialize: FunctionFragment;
    owner: FunctionFragment;
    place_order: FunctionFragment;
    renounce_ownership: FunctionFragment;
    set_asset_manager: FunctionFragment;
    set_execution_manager: FunctionFragment;
    set_max_expiration: FunctionFragment;
    set_min_expiration: FunctionFragment;
    set_pool: FunctionFragment;
    set_protocol_fee_recipient: FunctionFragment;
    set_royalty_manager: FunctionFragment;
    set_transfer_selector: FunctionFragment;
    transfer_ownership: FunctionFragment;
    update_order: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'cancel_order', values: [ContractIdInput, BigNumberish, SideInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'execute_order', values: [TakerOrderInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_asset_manager', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_execution_manager', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_max_expiration', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_min_expiration', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_pool', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_protocol_fee_recipient', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_royalty_manager', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_transfer_selector', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'initialize', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'owner', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'place_order', values: [MakerOrderInputInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'renounce_ownership', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'set_asset_manager', values: [ContractIdInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'set_execution_manager', values: [ContractIdInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'set_max_expiration', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'set_min_expiration', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'set_pool', values: [ContractIdInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'set_protocol_fee_recipient', values: [IdentityInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'set_royalty_manager', values: [ContractIdInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'set_transfer_selector', values: [ContractIdInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'transfer_ownership', values: [IdentityInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'update_order', values: [MakerOrderInputInput]): Uint8Array;

  decodeFunctionData(functionFragment: 'cancel_order', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'execute_order', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_asset_manager', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_execution_manager', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_max_expiration', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_min_expiration', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_pool', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_protocol_fee_recipient', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_royalty_manager', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_transfer_selector', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'initialize', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'owner', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'place_order', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'renounce_ownership', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'set_asset_manager', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'set_execution_manager', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'set_max_expiration', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'set_min_expiration', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'set_pool', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'set_protocol_fee_recipient', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'set_royalty_manager', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'set_transfer_selector', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'transfer_ownership', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'update_order', data: BytesLike): DecodedValue;
}

export class ThunderExchangeAbi extends Contract {
  interface: ThunderExchangeAbiInterface;
  functions: {
    cancel_order: InvokeFunction<[strategy: ContractIdInput, nonce: BigNumberish, side: SideInput], void>;
    execute_order: InvokeFunction<[order: TakerOrderInput], void>;
    get_asset_manager: InvokeFunction<[], ContractIdOutput>;
    get_execution_manager: InvokeFunction<[], ContractIdOutput>;
    get_max_expiration: InvokeFunction<[], BN>;
    get_min_expiration: InvokeFunction<[], BN>;
    get_pool: InvokeFunction<[], ContractIdOutput>;
    get_protocol_fee_recipient: InvokeFunction<[], IdentityOutput>;
    get_royalty_manager: InvokeFunction<[], ContractIdOutput>;
    get_transfer_selector: InvokeFunction<[], ContractIdOutput>;
    initialize: InvokeFunction<[], void>;
    owner: InvokeFunction<[], Option<IdentityOutput>>;
    place_order: InvokeFunction<[order_input: MakerOrderInputInput], void>;
    renounce_ownership: InvokeFunction<[], void>;
    set_asset_manager: InvokeFunction<[asset_manager: ContractIdInput], void>;
    set_execution_manager: InvokeFunction<[execution_manager: ContractIdInput], void>;
    set_max_expiration: InvokeFunction<[new_max_expiration: BigNumberish], void>;
    set_min_expiration: InvokeFunction<[new_min_expiration: BigNumberish], void>;
    set_pool: InvokeFunction<[pool: ContractIdInput], void>;
    set_protocol_fee_recipient: InvokeFunction<[protocol_fee_recipient: IdentityInput], void>;
    set_royalty_manager: InvokeFunction<[royalty_manager: ContractIdInput], void>;
    set_transfer_selector: InvokeFunction<[transfer_selector: ContractIdInput], void>;
    transfer_ownership: InvokeFunction<[new_owner: IdentityInput], void>;
    update_order: InvokeFunction<[order_input: MakerOrderInputInput], void>;
  };
}
