/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.75.0
  Forc version: 0.50.0
  Fuel-Core version: 0.22.1
*/

export type { AssetManagerAbi } from './AssetManagerAbi';

export { AssetManagerAbi__factory } from './factories/AssetManagerAbi__factory';
