import { AssetTable1Image, AssetTableImageNft1 } from "../assets";

export default {
  getMarketplace() {
    return [
      {
        collection: "CryptoPunks",
        volume: 123.21,
        floor: 123.21,
        change: 123.21,
        image: AssetTable1Image,
        lastSold: "",
        images: [AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1],
        sales: 1,
      },
      {
        collection: "CryptoPunks",
        volume: 123.21,
        floor: 123.21,
        change: -123.21,
        image: AssetTable1Image,
        lastSold: "",
        images: [AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1],
        sales: 1,
      },
      {
        collection: "CryptoPunks",
        volume: 123.21,
        floor: 123.21,
        image: AssetTable1Image,
        lastSold: "",
        images: [AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1],
        sales: 1,
      },
      {
        collection: "CryptoPunks",
        volume: 123.21,
        floor: 123.21,
        image: AssetTable1Image,
        lastSold: "",
        images: [AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1],
        sales: 1,
      },
      {
        collection: "CryptoPunks",
        volume: 123.21,
        floor: 123.21,
        image: AssetTable1Image,
        lastSold: "",
        images: [AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1],
        sales: 1,
      },
      {
        collection: "CryptoPunks",
        volume: 123.21,
        floor: 123.21,
        image: AssetTable1Image,
        lastSold: "",
        images: [AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1],
        sales: 1,
      },
      {
        collection: "CryptoPunks",
        volume: 123.21,
        floor: 123.21,
        image: AssetTable1Image,
        lastSold: "",
        images: [AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1],
        sales: 1,
      },
      {
        collection: "CryptoPunks",
        volume: 123.21,
        floor: 123.21,
        image: AssetTable1Image,
        lastSold: "",
        images: [AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1],
        sales: 1,
      },
      {
        collection: "CryptoPunks",
        volume: 123.21,
        floor: 123.21,
        image: AssetTable1Image,
        lastSold: "",
        images: [AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1],
        sales: 1,
      },
      {
        collection: "CryptoPunks",
        volume: 123.21,
        floor: 123.21,
        image: AssetTable1Image,
        lastSold: "",
        images: [AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1, AssetTableImageNft1],
        sales: 1,
      },
    ];
  },
};
