/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.38.1
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

import { Interface, Contract } from "fuels";
import type { Provider, Account, AbstractAddress } from "fuels";
import type { RoyaltyManagerAbi, RoyaltyManagerAbiInterface } from "../RoyaltyManagerAbi";

const _abi = {
  types: [
    {
      typeId: 0,
      type: "()",
      components: [],
      typeParameters: null,
    },
    {
      typeId: 1,
      type: "b256",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 2,
      type: "enum Identity",
      components: [
        {
          name: "Address",
          type: 10,
          typeArguments: null,
        },
        {
          name: "ContractId",
          type: 11,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 3,
      type: "enum Option",
      components: [
        {
          name: "None",
          type: 0,
          typeArguments: null,
        },
        {
          name: "Some",
          type: 4,
          typeArguments: null,
        },
      ],
      typeParameters: [4],
    },
    {
      typeId: 4,
      type: "generic T",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 5,
      type: "str[19]",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 6,
      type: "str[27]",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 7,
      type: "str[30]",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 8,
      type: "str[42]",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 9,
      type: "str[8]",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 10,
      type: "struct Address",
      components: [
        {
          name: "value",
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 11,
      type: "struct ContractId",
      components: [
        {
          name: "value",
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 12,
      type: "struct OwnershipRenounced",
      components: [
        {
          name: "previous_owner",
          type: 2,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 13,
      type: "struct OwnershipSet",
      components: [
        {
          name: "new_owner",
          type: 2,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 14,
      type: "struct OwnershipTransferred",
      components: [
        {
          name: "new_owner",
          type: 2,
          typeArguments: null,
        },
        {
          name: "previous_owner",
          type: 2,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 15,
      type: "struct RoyaltyInfo",
      components: [
        {
          name: "collection",
          type: 11,
          typeArguments: null,
        },
        {
          name: "receiver",
          type: 2,
          typeArguments: null,
        },
        {
          name: "fee",
          type: 17,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 16,
      type: "struct RoyaltyRegistryEvent",
      components: [
        {
          name: "royalty_info",
          type: 15,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 17,
      type: "u64",
      components: null,
      typeParameters: null,
    },
  ],
  functions: [
    {
      inputs: [],
      name: "get_royalty_fee_limit",
      output: {
        name: "",
        type: 17,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "collection",
          type: 11,
          typeArguments: null,
        },
      ],
      name: "get_royalty_info",
      output: {
        name: "",
        type: 3,
        typeArguments: [
          {
            name: "",
            type: 15,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [],
      name: "initialize",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [],
      name: "owner",
      output: {
        name: "",
        type: 3,
        typeArguments: [
          {
            name: "",
            type: 2,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "collection",
          type: 11,
          typeArguments: null,
        },
        {
          name: "receiver",
          type: 2,
          typeArguments: null,
        },
        {
          name: "fee",
          type: 17,
          typeArguments: null,
        },
      ],
      name: "register_royalty_info",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [],
      name: "renounce_ownership",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "new_fee_limit",
          type: 17,
          typeArguments: null,
        },
      ],
      name: "set_royalty_fee_limit",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "new_owner",
          type: 2,
          typeArguments: null,
        },
      ],
      name: "transfer_ownership",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
  ],
  loggedTypes: [
    {
      logId: 0,
      loggedType: {
        name: "",
        type: 5,
        typeArguments: null,
      },
    },
    {
      logId: 1,
      loggedType: {
        name: "",
        type: 13,
        typeArguments: [],
      },
    },
    {
      logId: 2,
      loggedType: {
        name: "",
        type: 8,
        typeArguments: null,
      },
    },
    {
      logId: 3,
      loggedType: {
        name: "",
        type: 8,
        typeArguments: null,
      },
    },
    {
      logId: 4,
      loggedType: {
        name: "",
        type: 7,
        typeArguments: null,
      },
    },
    {
      logId: 5,
      loggedType: {
        name: "",
        type: 16,
        typeArguments: [],
      },
    },
    {
      logId: 6,
      loggedType: {
        name: "",
        type: 9,
        typeArguments: null,
      },
    },
    {
      logId: 7,
      loggedType: {
        name: "",
        type: 12,
        typeArguments: [],
      },
    },
    {
      logId: 8,
      loggedType: {
        name: "",
        type: 9,
        typeArguments: null,
      },
    },
    {
      logId: 9,
      loggedType: {
        name: "",
        type: 6,
        typeArguments: null,
      },
    },
    {
      logId: 10,
      loggedType: {
        name: "",
        type: 9,
        typeArguments: null,
      },
    },
    {
      logId: 11,
      loggedType: {
        name: "",
        type: 14,
        typeArguments: [],
      },
    },
  ],
  messagesTypes: [],
  configurables: [],
};

export class RoyaltyManagerAbi__factory {
  static readonly abi = _abi;
  static createInterface(): RoyaltyManagerAbiInterface {
    return new Interface(_abi) as unknown as RoyaltyManagerAbiInterface;
  }
  static connect(id: string | AbstractAddress, accountOrProvider: Account | Provider): RoyaltyManagerAbi {
    return new Contract(id, _abi, accountOrProvider) as unknown as RoyaltyManagerAbi;
  }
}
