/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.57.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.4
*/

export type { NFTContractAbi } from './NFTContractAbi';

export { NFTContractAbi__factory } from './factories/NFTContractAbi__factory';
