export enum PATHS {
  HOME = "/",
  LOGIN = "/login",
  MARKETPLACE = "/marketplace",
  COLLECTION = "/collection/:collectionId",
  COLLECTION_ITEMS = "",
  COLLECTION_ACTIVITY = "activity",
  RANKINGS = "/rankings",
  NFT_DETAILS = "/nft-details/:nftId",
  PROFILE = "/profile",
  PROFILE_OWNED = "",
  PROFILE_ACTIVITY = "activity",
  PROFILE_OFFER = "offer",
  BULK_LISTING = "/bulk-listing",
  SETTINGS = "/settings",
  SETTINGS_PROFILE = "profile",
  SETTINGS_NOTIFICATION = "notification",
}
