export enum PATHS {
  HOME = "/",
  LOGIN = "/login",
  MARKETPLACE = "/marketplace",
  COLLECTION = "/collection/:collectionId",
  COLLECTION_ITEMS = "",
  COLLECTION_ACTIVITY = "activity",
  RANKINGS = "/rankings",
  NFT_DETAILS = "/nft-details/:nftId",
  PROFILE = "/profile",
  PROFILE_OWNED = "",
  PROFILE_ACTIVITY = "/profile/activity",
  PROFILE_OFFER = "/profile/offer",
  PROFILE_LIKED = "/profile/liked",
  BULK_LISTING = "/bulk-listing",
  SETTINGS = "/settings",
  SETTINGS_PROFILE = "/settings/profile",
  SETTINGS_NOTIFICATION = "/settings/notification",
  USER = "/user/:userId",
  USER_OWNED = "",
  USER_ACTIVITY = "/user/:userId/activity",
  USER_OFFER = "/user/:userId/offer",
  USER_LIKED = "/user/:userId/liked",
}
